{
 ### Environment Parameters
  mode: train,   # train, calibrate
  cuda: true,
  pin_memory: true,
  wandb: false,
  worker: 8,
  log_interval: 9999,
  save_interval: 1,
  saved_model_directory: 'model_checkpoints',
  train_fold: 1,  # fold train data and start validate
  project_name: 'ambiguous_label',
  CUDA_VISIBLE_DEVICES: '0',

  ### Train Parameters
  model_name: 'Swin',
  dataloader: 'Image2Image',
  num_class: 2,
  criterion: 'CE',
  task: 'segmentation',
  input_space: 'RGB',
  input_channel: 3,
  input_size: [640, 480],  # (height, width)
  crop_size: '320',
  # resolution: [1280, 1024],
  scheduler: 'CosineAnnealingLR', # WarmupCosine, CosineAnnealingLR
  batch_size: 8,
  epoch: 10000,
  lr: 0.0001,
  class_weight: [1.0, 1.0],

   ### Data Parameters
  transform_blur: true,
  transform_jitter: true,
  transform_hflip: true,
  transform_perspective: true,
  transform_cutmix: true,
  transform_rand_resize: true,
  transform_rand_crop: 224,

  train_x_path: 'awesome/path/to/dataset',
  train_y_path: 'awesome/path/to/dataset',
  val_x_path:   'awesome/path/to/dataset',
  val_y_path:   'awesome/path/to/dataset',
}