{
 ### Environment Parameters
  debug: true,
  mode: 'test', # test, inference
  cuda: true,
  worker: 4,
  CUDA_VISIBLE_DEVICES: '0',

  task: 'landmark', # segmentation, classification, regression, landmark
  model_name: 'eva_l_reg',
    num_class: 212,
    in_channel: 3,
    freeze_backbone: false,
    normalization: 'InstanceNorm1d', # BatchNorm1d, InstanceNorm1d, LayerNorm
    activation: 'ReLU', # ReLU, SiLU
    dropblock: true,

  criterion: 'WingLoss',

  dataloader: 'Image2Landmark',
    weighted_sampler: False,
    batch_size: 32,
    input_size: [336, 336],  # [h, w]

  data_cache: false,
  draw_results: true,
  model_path: '/path/to/model.pt',

  valid_x_path:   '/path/to/data/val/input',
  valid_y_path:   '/path/to/data/val/label',
  valid_csv_path: '/path/to/data/val/test.csv',
  image_col: 'img_path',
}