{
  debug: true,
  mode: 'test', # test, inference
  cuda: true,
  worker: 4,
  CUDA_VISIBLE_DEVICES: '0',

  task: 'segmentation', # segmentation, classification, regression, landmark
  model_name: 'Swin_t_semanticSegmentation',
    num_class: 2,
    in_channel: 3,
    base_c: 96,

  dataloader: 'Image',
    weighted_sampler: False,
    batch_size: 32,
    input_size: [512, 512],  # (height, width)

  criterion: 'WingLoss',
  draw_results: True,
  model_path: 'pretrained/Swin_t_semanticSegmentation-Epoch_475-mIoU_0.9508-folds_0.pt',

  ### Data parameters
  valid_csv_path: '/path/to/test.csv',
}