{
 ### Environment Parameters
  mode: inference,
  cuda: true,
  pin_memory: true,
  worker: 4,
  CUDA_VISIBLE_DEVICES: '2',

  task: 'classification', # segmentation, classification
  model_name: 'ResNet18_multihead',
  criterion: 'CE',  # CE, DiceBCE
  dataloader: 'Image2Vector', # Image2Image, Image2Vector
  num_class: 2,
  input_space: 'RGB',
  input_channel: 3,
  input_size: [512, 512],  # (height, width)
  mount_data_on_memory: false,
  draw_results: false,

  model_path: 'path/to/model.pt',

  val_x_path:   '/path/to/data/val/input',
  val_y_path:   '/path/to/data/val/label',
  val_csv_path: '/path/to/data/val.csv',
}
