{
 ### Environment Parameters
  debug: true,
  mode: test, # test, validation
  cuda: true,
  pin_memory: true,
  worker: 4,
  CUDA_VISIBLE_DEVICES: '1',

  task: 'classification', # segmentation, classification
  model_name: 'ConvNextV2_classification',  # ConvNextV2_classification
    num_class: 25,
    in_channel: 3,
    hidden_dims: 1024,
  criterion: 'CrossEntropyLoss',  # CE, DiceBCE
  dataloader: 'Image2Vector', # Image2Image, Image2Vector
    weighted_sampler: False,
    batch_size: 32,
  input_size: [256, 256],  # (height, width)
  mount_data_on_memory: false,
  draw_results: false,

  model_path: 'pretrained/ConvNextV2_classification_Epoch_34_f1_0.9672608239975305.pt',

  val_x_path:   '/path/to/data/val/input',
  val_y_path:   '/path/to/data/val/label',
  val_csv_path: '/path/to/data/val/test.csv',
  image_col: 'img_path',
}
