command:
  - ${env}
  - python3
  - ${program}
  - ${args}

method: bayes
metric:
  goal: maximize
  name: 'Best f1'

parameters:
  debug:
    values:
      - false
  mode:
    values:
      - 'train'
  cuda:
    values:
      - true
  pin_memory:
      values:
      - true
  wandb:
    values:
      - true
  worker:
    values:
      - 8
  save_interval:
    values:
      - 9999
  saved_model_directory:
    values:
      - 'model_ckpt_sweep'
  train_fold:
    values:
      - 4
  project_name:
    values:
      - 'wandb_sweeper'
  CUDA_VISIBLE_DEVICES:
    values:
      - '0,1'
  task:
    values:
      - 'classification'
  model_name:
    values:
      - 'Swin_l_classification'
  num_class:
    values:
      - 25
  in_channel:
    values:
      - 3
  hidden_dims:
    values:
      - 1024
  freeze_backbone:
    values:
      - false
  normalization:
    distribution: 'categorical'
    values:
      - 'BatchNorm1d'
      - 'InstanceNorm1d'
      - 'LayerNorm'
  activation:
    distribution: 'categorical'
    values:
      - 'ReLU'
      - 'SiLU'
  dropblock:
    distribution: 'categorical'
    values:
      - true
      - false
  dataloader:
    values:
      - 'Image2Vector'
  weighted_sampler:
    values:
      - false
  batch_size:
    values:
      - 32
  criterion:
    distribution: 'categorical'
    values:
      - 'LabelSmoothingCrossEntropyLoss'
      - 'CrossEntropyLoss'
  input_size:
    values:
      - [256, 256]
  optimizer:
    values:
      - 'AdamW'
  lr:
    distribution: uniform
    min: 0.000005
    max: 0.00005
  lr_min:
    distribution: uniform
    min: 0.0000001
    max: 0.00001
  weight_decay:
    values:
      - 0.05
  scheduler:
    values:
      - 'WarmupCosine'
  cycles:
    values:
      - 5
  warmup_epoch:
      values:
      - 1
  epoch:
    values:
      - 30
  early_stop_epoch:
    values:
      - 15
  model_path:
    values:
      - 'path/to/model.pt'
  data_cache:
    values:
      - true

  transform_blur:
    distribution: uniform
    min: 0.0
    max: 0.7
  transform_clahe:
    distribution: uniform
    min: 0.0
    max: 0.5
  transform_cutmix:
    values:
      - 0
  transform_fancyPCA:
    distribution: uniform
    min: 0.0
    max: 0.5
  transform_fog:
    distribution: uniform
    min: 0.0
    max: 0.3
  transform_g_noise:
    distribution: uniform
    min: 0.0
    max: 0.7
  transform_jitter:
    distribution: uniform
    min: 0.0
    max: 0.5
  transform_hflip:
    values:
      - 0.5
  transform_vflip:
    values:
      - 0
  transform_jpeg:
    distribution: uniform
    min: 0.0
    max: 0.8
  transform_mixup:
    distribution: uniform
    min: 0.0
    max: 1.0
  transform_perspective:
    distribution: uniform
    min: 0.0
    max: 0.5
  transform_rand_resize:
    values:
      - 0
  transform_rand_crop:
    values:
      - 256
  transform_rain:
    distribution: uniform
    min: 0.0
    max: 0.3

  train_csv_path:
    values:
      - 'path/to/train.csv'
  val_csv_path:
    values:
      - 'path/to/valid.csv'
  image_col:
    values:
      - 'img_path'

program: main.py