{
  ### Environment Parameters
  debug: true,
  mode: 'train',   # train
  cuda: true,
  wandb: true,
  worker: 8,
  saved_model_directory: 'model_ckpt',
  train_fold: 5,  # The number of validation while training
  project_name: 'wandb_project',
  CUDA_VISIBLE_DEVICES: '2',

  ### Train Parameters
  task: 'regression',

  model_name: 'Deit3_l_reg',  # ConvNextV2_classification, Swin_t_classification
    num_class: 212,
    in_channel: 3,
    freeze_backbone: false,
    normalization: 'InstanceNorm1d', # BatchNorm1d, InstanceNorm1d, LayerNorm
    activation: 'ReLU', # ReLU, SiLU
    dropblock: true,

  dataloader: 'Image2Landmark',
    weighted_sampler: False,
    batch_size: 32,
    input_size: [224, 224],  # (height, width)

  criterion: 'WingLoss',  # LabelSmoothingCrossEntropyLoss, WingLoss
  optimizer: 'AdamW',
    lr: 0.000005,
    lr_min: 0.0000005,
    weight_decay: 0.05,
    scheduler: 'WarmupCosine',
      cycles: 5,
      warmup_epoch: 0,

  epoch: 300,
  early_stop_epoch: 30,
  model_path: '', # imagenet/swin_tiny_patch4_window7_224.pth

  ### Augmentation parameters
  data_cache: false,

  transform_blur: 0.1,
  transform_clahe: 0.1,
  transform_cutmix: 0.0,
  transform_coarse_dropout: 0.5,
  transform_fancyPCA: 0.1,
  transform_fog: 0.05,
  transform_g_noise: 0.1,
  transform_jitter: 0.1,
  transform_hflip: 0.0,
  transform_vflip: 0.0,
  transform_jpeg: 0.5,
  transform_perspective: 0.0,
  transform_rand_resize: 0.0,
  transform_rand_crop: 224,
  transform_rain: 0.05,
  transform_landmark_rotate: 0.5,
  transform_landmark_hflip: 0.5,

  train_csv_path: '/path/to/train.txt',
  valid_csv_path: '/path/to/valid.txt',
}
