{
 ### Environment Parameters
 mode: train,  # train
 cuda: true,
 pin_memory: true,
 wandb: false,
 worker: 16,
 log_interval: 10000,
 save_interval: 1,
 saved_model_directory: 'model_checkpoints',
 train_fold: 1,  # fold train data and start validate. 1 for default
 project_name: 'my_wandb_project',
 CUDA_VISIBLE_DEVICES: '0',

 ### Train Parameters
 model_name: 'ResNet18_multihead',
 dataloader: 'Image2Vector',
 num_class: 6,
 criterion: 'CE',
 task: 'classification',
 input_space: 'RGB',
 input_channel: 3,
 input_size: [480, 640],  # (height, width)
 scheduler: 'CosineAnnealingLR',
 batch_size: 128,
 epoch: 1000,
 lr: 0.001,
 class_weight: [1.0, 1.0],
 model_path: 'pretrained/imagenet/pretrained_model.pt',  # set empty to deactivate

   ### Data Parameters
  transform_blur: true,
  transform_jitter: true,
  transform_hflip: true,
  transform_perspective: true,
  transform_cutmix: true,
  transform_rand_resize: true,
  transform_rand_crop: 224,

 train_csv_path: 'awesome/path/to/csv/tmp.csv',
 val_csv_path:   'awesome/path/to/csv/tmp.csv',
}