{
 ### Environment Parameters
  mode: train,   # train
  cuda: true,
  pin_memory: true,
  wandb: false,
  worker: 8,
  log_interval: 100,
  save_interval: 99999,
  saved_model_directory: 'model_checkpoints',
  train_fold: 1,  # fold train data and start validate
  project_name: 'lululab_darkcircle_flush_segmentation',
  CUDA_VISIBLE_DEVICES: '2',

  ### Train Parameters
  task: 'segmentation_score_cycle_repr',
  model_name: 'DiNAT_s_T_segMap_score_multi_stem_repr',
  dataloader: 'Image2Image',
  dataloader_score: 'Image2Vector',
  dataloader_unsup: 'Image',
  num_class: 3,
  criterion: 'CE',
  criterion_score: 'MSE',
  criterion_unsup: 'InfoNCE',
  input_space: 'RGB',
  input_channel: 3,
  input_size: [512, 512],  # (height, width)
  optimizer: 'AdamW',
    lr: 0.0001,
    scheduler: 'WarmupCosine',   # WarmupCosine, CosineAnnealingLR
    cycles: 100,
    warmup_epoch: 20,
    weight_decay: 0.05,
    early_stop_epoch: 400,
  batch_size: 32,
  epoch: 10000,
  ema_decay: 0, # set 0 to deactivate
  class_weight: [1.0, 1.0],
  model_path: 'pretrained/ImageNet/dinat_s_tiny_in1k_224.pth',  # pretrained/ImageNet/swin_tiny_patch4_window7_224.pth, dinat_s_tiny_in1k_224.pth

   ### Data Parameters
  data_cache: false,
  transform_blur: 0.3,
  transform_clahe: 0.2,
  transform_rain: 0.1,
  transform_fog: 0.1,
  transform_g_noise: 0.1,
  transform_fancyPCA: 0.2,
  transform_jitter: 0.2,
  transform_hflip: 0.5,
  transform_vflip: 0.0,
  transform_jpeg: 0.5,
  transform_perspective: 0.3,
  transform_rand_resize: 0.7,
  transform_rand_crop: 224,
  transform_cutmix: 0.8,
  transform_mixup: 1.0,

  train_x_path: '/lulu_data/data/ssy/lululab/darkcircle_flush/230410_labeler_round_4/train/input',
  train_y_path: '/lulu_data/data/ssy/lululab/darkcircle_flush/230410_labeler_round_4/train/label',
  train_csv_path: '/lulu_data/data/ssy/lululab/darkcircle_flush/230515_score_round_3/train_CYS.csv',
  train_x_unsup_path: '/lulu_data/data/ssy/lululab/aws_55000/all_imgs_jpeg100_crop_17000',
  val_x_path:   '/lulu_data/data/ssy/lululab/darkcircle_flush/230410_labeler_round_4/val/input',
  val_y_path:   '/lulu_data/data/ssy/lululab/darkcircle_flush/230410_labeler_round_4/val/label',
  val_csv_path: '/lulu_data/data/ssy/lululab/darkcircle_flush/230515_score_round_3/val_CYS.csv',
}