{
  ### Environment Parameters
  debug: false,
  mode: train,   # train
  cuda: true,
  pin_memory: true,
  wandb: true,
  worker: 8,
  log_interval: 9999,
  save_interval: 9999,
  saved_model_directory: 'model_ckpt',
  train_fold: 5,  # The number of validation while training
  project_name: 'wandb_project',
  CUDA_VISIBLE_DEVICES: '2',

  ### Train Parameters
  task: 'classification',
  model_name: 'ConvNextV2_classification',  # ConvNextV2_classification, Swin_t_classification
    num_class: 25,
    in_channel: 3,
    hidden_dims: 1024,
  dataloader: 'Image2Vector',
    weighted_sampler: False,
    batch_size: 32,
  criterion: 'LabelSmoothingCrossEntropyLoss',
  input_size: [256, 256],  # (height, width)
  optimizer: 'AdamW',
    lr: 0.000001,
    lr_min: 0.00000001,
    weight_decay: 0.05,
    scheduler: 'WarmupCosine',
      cycles: 5,
      warmup_epoch: 0,
  epoch: 90,
  early_stop_epoch: 20,
  model_path: '', # pretrained/swin_tiny_patch4_window7_224.pt,

  ### Augmentation parameters
  data_cache: true,
  transform_blur: 0.5,
  transform_clahe: 0.3,
  transform_cutmix: 0.0,
  transform_fancyPCA: 0.3,
  transform_fog: 0.1,
  transform_g_noise: 0.3,
  transform_jitter: 0.3,
  transform_hflip: 0.5,
  transform_vflip: 0.0,
  transform_jpeg: 0.5,
  transform_mixup: 0.5,
  transform_perspective: 0.3,
  transform_rand_resize: 0.9,
  transform_rand_crop: 228,
  transform_rain: 0.1,

  train_csv_path: '/path/to/train/train.csv',
  val_csv_path:   '/path/to/train/valid.csv',
  image_col: 'img_path',
}