{
  ### Environment Parameters
  debug: true,
  mode: 'train',   # train
  cuda: true,
  wandb: true,
  worker: 8,
  saved_model_directory: 'model_ckpt',
  train_fold: 4,  # The number of validation in 1 train epoch
  project_name: 'wandb_project',
  CUDA_VISIBLE_DEVICES: '0',

  ### Train Parameters
  task: 'classification',

  model_name: 'Swin_s_classification',
    num_class: 25,
    in_channel: 3,
    freeze_backbone: false,
    normalization: 'InstanceNorm1d', # BatchNorm1d, InstanceNorm1d, LayerNorm
    activation: 'SiLU', # ReLU, SiLU
    dropblock: true,

  dataloader: 'Image2Vector',
    weighted_sampler: False,
    batch_size: 64,
    input_size: [256, 256],  # (height, width)

  criterion: 'LabelSmoothingCrossEntropyLoss',  # LabelSmoothingCrossEntropyLoss, CrossEntropyLoss
  optimizer: 'AdamW',
    lr: 0.00005,
    lr_min: 0.000001,
    weight_decay: 0.05,
    scheduler: 'WarmupCosine',
      cycles: 5,
      warmup_epoch: 0,

  epoch: 100,
  early_stop_epoch: 30,
  model_path: '/path/to/model.pt',

  ### Augmentation parameters
  data_cache: true,
  transform_blur: 0.5,
  transform_clahe: 0.5,
  transform_cutmix: 0.0,
  transform_coarse_dropout: 0.7,
  transform_fancyPCA: 0.5,
  transform_fog: 0.3,
  transform_g_noise: 0.5,
  transform_jitter: 0.1,
  transform_hflip: 0.5,
  transform_vflip: 0.0,
  transform_jpeg: 0.5,
  transform_mixup: 0.7,
  transform_perspective: 0.1,
  transform_rand_resize: 0.0,
  transform_rand_crop: 256,
  transform_rain: 0.1,

  train_csv_path_folds: ['/path/to/train_fold_0.csv',
                         '/path/to/train_fold_1.csv',
                         '/path/to/train_fold_2.csv',
                         '/path/to/train_fold_3.csv',
                         '/path/to/train_fold_4.csv',],
  valid_csv_path_folds: ['/path/to/valid_fold_0.csv',
                         '/path/to/valid_fold_1.csv',
                         '/path/to/valid_fold_2.csv',
                         '/path/to/valid_fold_3.csv',
                         '/path/to/valid_fold_4.csv',],
}
